name    'jtopjian-sshkeys'
version '0.5.0'
source 'git@github.com/jtopjian/puppet-sshkeys.git'
author 'Joe Topjian'
license 'Apache License, Version 2.0'
summary 'sshkeys puppet module'
description 'Module to manage SSH public keys as facter facts'
project_page 'https://github.com/jtopjian/puppet-sshkeys'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
dependency 'dalen/puppetdbquery', '>= 1.3.2'
