name    'puppet-sshkeys'
version '0.0.1'
source 'git@github.com/jtopjian/puppet-sshkeys.git'
author 'Joe Topjian'
license 'Apache License, Version 2.0'
summary 'sshkeys puppet module'
description 'Module to manage SSH public keys as facter facts'
project_page 'https://github.com/jtopjian/puppet-sshkeys'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
